# NumPy Arrays:

In [1]:
import sys
print(sys.executable)

C:\Users\u17185\AppData\Local\Continuum\anaconda3\envs\numpyenv\python.exe


In [16]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
my_list

[1, 2, 3]

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [13]:
randint(2,10)

5

In [14]:
from numpy.random import randint

## Numpy does not create copies of arrays. To clone, use the "array_name.copy()" method. Otherwise, changes to the newest array will modify the original one.

In [18]:
arr = np.array([[0,1,2], [3,4,5], [6,7,8]])

In [19]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr[2:,:1]
    

array([[6]])

In [25]:
arr.dtype

dtype('int32')

In [28]:
arr.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])